"""baseline schema

Captures the schema this app already had before Alembic was introduced —
the 4 tables from app/models.py, with every column app/database.py's old
_ADDED_COLUMNS stopgap had already merged in (starting_balance, balance,
simplefin_account_id, simplefin_connection_id, reported_balance,
reported_balance_as_of). Autogenerated against an empty database and
verified to match app/models.py exactly, then hand-edited only to give it
a stable revision id ("0001") instead of a random hash — every future
migration in this app chains off this fixed id, and app/database.py's
run_migrations() stamps a pre-Alembic existing database at exactly this
revision (never a later "head", so any migration added after this one
still runs against it).

Revision ID: 0001
Revises:
Create Date: 2026-08-29
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "simplefin_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_url", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("institution", sa.String(length=120), nullable=True),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("starting_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("simplefin_account_id", sa.String(length=255), nullable=True),
        sa.Column("simplefin_connection_id", sa.Integer(), nullable=True),
        sa.Column("reported_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("reported_balance_as_of", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["simplefin_connection_id"], ["simplefin_connections.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("transactions")
    op.drop_table("accounts")
    op.drop_table("simplefin_connections")
    op.drop_table("categories")
